name: Check locale
on: 
    pull_request:
      branches: 
       - main 
      paths:
       - 'resources/profiles/**'
       - ".github/workflows/check_profiles.yml"

jobs:
  check_translation:
    name: Check profiles
    runs-on: ubuntu-22.04
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      # download
      - name: Download 
        working-directory: ${{ github.workspace }}
        run: |
          curl -LJO https://github.com/SoftFever/Orca_tools/releases/download/1/OrcaSlicer_profile_validator_ubuntu
          chmod +x ./OrcaSlicer_profile_validator_ubuntu

      # validate profiles
      - name: validate profiles
        run: |
          ./OrcaSlicer_profile_validator_ubuntu -p ${{ github.workspace }}/resources/profiles -l 2

        
